AllCops:
    NewCops: disable

Metrics/AbcSize:
    Max: 100

Style/FrozenStringLiteralComment:
    Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/AsciiComments:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Layout/LineLength:
  Max: 100

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

Layout/HeredocIndentation:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
