AllCops:
  NewCops: disable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/AsciiComments:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Layout/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 30

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/HeredocIndentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Documentation:
  Enabled: false
